[theme]
base = "dark"

# Colores generales (estas opciones siguen siendo v치lidas)
textColor = "#ffffff"
primaryColor = "#eb3131"
backgroundColor = "#080f1a"
secondaryBackgroundColor = "#2e3238"

# Para la fuente, puedes usar 'font' con un valor v치lido
# streamlit solo soporta 'sans serif', 'serif', 'monospace' o una fuente web
font = "sans serif"

[global]
# Esta configuraci칩n a veces ayuda a forzar el entorno de ejecuci칩n
defaultLanguage = "es"

[server]
